version: '3.3'


services:
   urlshortnerclient:
     #build: .
     image: myurlshortnerclient_urlshortnerclient
     container_name: urlshortnerclientapp
     stdin_open: true # docker run -i
     tty: true
     
     ports:
       - "3000:3000"
     restart: always
     
        
     environment:
      REACT_APP_API_URL: http://urls.com/yourls-api.php?
      REACT_APP_API_USERNAME: username
      REACT_APP_API_PASSWORD: password
       
     



  


    